version: "3.7"

services:
  spring-boot-sample-tomcat:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: production