[SERVICE]
    Flush 1
    Grace 30
    Parsers_File /fluent-bit/etc/parsers.conf

# ELBヘルスチェックログ除外
[FILTER]
    Name grep
    Match *-firelens-*
    Exclude log ^(?=.*ELB-HealthChecker\/2\.0).*$

[FILTER]
    Name   grep
    Match  *-firelens-*
    Exclude log ^(?=.*"request".*"uri":"\/actuator\/health").*$


[FILTER]
    name                  multiline
    match                 *
    multiline.key_content log
    multiline.parser      java

# ECSからはこんなログが出力されてくる
# logの部分にアプリのログが入ってきて、あとはかってにFirelens/Fluentbitがセットしてそう
# アプリのログはLogbackがjson形式で出力しているが「"」などはbaskslashでescapeされている  
# {    "container_id": "xxxxx-3798276243",    "container_name": "spring-boot-sample-tomcat",    "source": "stdout",    "log": "{\"@timestamp\":\"2023-08-23T07:38:55.618640529Z\",\"@version\":\"1\",\"message\":\"Default Message.\",\"logger_name\":\"nu.mine.kino.web.EchoController\",\"thread_name\":\"http-nio-8080-exec-9\",\"level\":\"INFO\",\"level_value\":20000}",    "ecs_cluster": "xxxcluster",    "ecs_task_arn": "arn:aws:ecs:ap-northeast-1:70604xxx0076932:task/xxxcluster/xxx",    "ecs_task_definition": "spring-boot-taskdefinition:9"}

# log部を抽出して、中のescapeされた文字列をあらためてJSON化
[FILTER]
    Name parser
    Match *-firelens-*
    Key_Name log
    Parser json
    # Preserve_Key On
    Reserve_Data On

    # Preserve_Key On 該当キー(Key_Name)の元データ(=log)も残す
    # Reserve_Data On 他のデータ(key3)も残す
    # OFF/OFF {"key1"=>"v1", "key2"=>"v2"}
    # OFF/ON  {"key1"=>"v1", "key2"=>"v2", "key3"=>"v3"}
    # ON/ON   {"key1"=>"v1", "key2"=>"v2", "key3"=>"v3", "log"=>"{"key1":"v1","key2":"v2"}"}
    # ON/OFF  {"key1"=>"v1", "key2"=>"v2"} ??
    # cf https://docs.fluentbit.io/manual/pipeline/filters/parser

# エラーログにタグ付け
# 2. appType=FW のログを fw-$container_id に振る
[FILTER]
    Name          rewrite_tag
    Match         *-firelens-*
    Rule          $appType ^FW$ fw-$container_id false

# 3. fw-$container_id タグに対して、level=ERROR のログを error-$container_id に振る
[FILTER]
    Name          rewrite_tag
    Match         fw-*
    Rule          $level ^ERROR$ error-$container_id false

# 4. fw-$container_id タグに対して、logType=request_response のログを request_response-$container_id に振る
[FILTER]
    Name          rewrite_tag
    Match         fw-*
    Rule          $logType ^request_response$ request_response-$container_id false


# errorタグをCloudWatch Logsへ
[OUTPUT]
    Name cloudwatch_logs
    Match error-*
    region ap-northeast-1
    auto_create_group true
    log_group_name /aws/ecs/spring-boot-sample-tomcat-error
    log_stream_prefix error/
    # log_retention_days 30

# ロググループ : /aws/ecs/spring-boot-sample-tomcat-error
# ストリーム: error/error-[コンテナID？ぽいなにか]
# とかになっていました

[OUTPUT]
    Name s3
    Match fw-*
    region ap-northeast-1
    bucket masatomix-fluent-bit
    total_file_size 1M
    upload_timeout 1m
    use_put_object On
# s3://masatomix-fluent-bit/fluent-bit-logs/fw-[コンテナID？ぽいなにか]/2025/09/22/08/16/03-xxxx
# とかになってる(日付みたいなところは、UTCなので注意。日本時間-9h)


[OUTPUT]
    Name s3
    Match request_response-*
    region ap-northeast-1
    bucket masatomix-fluent-bit-req-res
    total_file_size 1M
    upload_timeout 1m
    use_put_object On

# s3://masatomix-fluent-bit-req-res/fluent-bit-logs/request_response-[コンテナID？ぽいなにか]/2025/09/22/08/16/02-xxxxxxx
# とかになってる(日付みたいなところは、UTCなので注意。日本時間-9h)


[OUTPUT]
    Name s3
    Match *-firelens-*
    region ap-northeast-1
    bucket masatomix-fluent-bit
    total_file_size 1M
    upload_timeout 1m
    use_put_object On
# s3://masatomix-fluent-bit/fluent-bit-logs/app-firelens-[コンテナID？ぽいなにか]/2025/09/22/08/11/36-xxxxxx
# とかになってる(日付みたいなところは、UTCなので注意。日本時間-9h)


# [OUTPUT]
#     Name cloudwatch_logs
#     # Match * # どれも出るので、error-$container_id タグ付けたデータもココに出る(タグがStreamIdになるので別のstreamで。)
#     Match *-firelens-*
#     region ap-northeast-1
#     auto_create_group true
#     log_group_name /aws/ecs/spring-boot-sample-tomcat-console
#     log_stream_prefix console/
#     # log_retention_days 30